### ISSUE TITLE
SNPEff error

### ISSUE THREAD

**Issue by JudithNeukamm** [Integrative-Transcriptomics/MUSIAL#4]
I always get an error when running SNPEff:
SNPEffCommand: 
java -jar snpEff.jar mySample snvVcfForSnpEff.vcf 
Exception in thread "main" java.lang.NullPointerException
	at datastructure.SNVTable.toStringWithSNPEffInfos(SNVTable.java:412)
	at tools.Analyzer.run(Analyzer.java:558)
	at tools.Analyzer.<init>(Analyzer.java:394)
	at main.Musial.main(Musial.java:27)

**Comment by zxmmx04** [comment]
If you run it without snpeff, does it work without errors and do you get a result?

**Comment by JudithNeukamm** [comment]
It works perfect without snpeff.

**Comment by zxmmx04** [comment]
Strange,
I ran several tests here and can't reproduce the error, can you maybe give me access to a minimum test dataset where the error occurs?

Thank you

**Comment by JudithNeukamm** [comment]
Hi Alex, 

sorry for the late response. 
I tried it on some published T. pallidum genomes (CDC2, Gauthier, DAL-1, and Chicago) and I get the same error as with the leprosy genomes before. 
I can send you the data directly if you wish. 

Best, Judith

**Comment by JudithNeukamm** [comment]
Hm it worked now. It could have been a problem with the naming. 
But thanks for checking :)
